"use client";

import { useMemo, useState } from "react";

type Decision = { source_id: string; target_id: string | null; relationship: string; status: "matched" | "unmatched" | "ambiguous"; confidence: number; evidence: string[]; exception_category: string | null };
type Report = { records_processed: number; auto_match_rate: number; verified_matching_accuracy: number; unresolved_exceptions: number; processing_time_ms: number; exception_categories: Record<string, number>; decisions: Decision[] };
const words = (value: string) => value.replaceAll("_", " ");

export function ReconciliationWorkbench() {
  const [report, setReport] = useState<Report | null>(null);
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const exceptions = useMemo(() => report?.decisions.filter((decision) => decision.status !== "matched") ?? [], [report]);
  const selected = exceptions.find((decision) => decision.source_id === selectedId) ?? exceptions[0] ?? null;
  async function runBatch() { setState("loading"); setError(null); try { const response = await fetch("/api/reconciliation", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "The reconciliation run could not complete."); setReport(body); setSelectedId(null); setState("success"); } catch (cause) { setError(cause instanceof Error ? cause.message : "The reconciliation run could not complete."); setState("error"); } }
  function reset() { setReport(null); setSelectedId(null); setError(null); setState("idle"); }
  const metrics = [["Records processed", report ? String(report.records_processed) : "—"], ["Auto-match rate", report ? `${Math.round(report.auto_match_rate * 100)}%` : "—"], ["Verified accuracy", report ? `${Math.round(report.verified_matching_accuracy * 100)}%` : "—"], ["Unresolved", report ? String(report.unresolved_exceptions) : "—"]];
  return <main className="workbench">
    <header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true">L</span>LedgerLens</div><p className="source-label">Synthetic demo data only · no live Razorpay integration</p></header>
    <section className="runbar" aria-labelledby="workspace-heading"><div><p className="eyebrow">Reconciliation workspace</p><h1 id="workspace-heading">Close the batch. Keep the uncertainty visible.</h1><p className="lede">Deterministic rules reconcile the evidence. Exceptions stay open until a human reviews them.</p></div><div className="run-controls"><label className="batch-picker">Batch<select aria-label="Select reconciliation batch" defaultValue="august"><option value="august">August demo merchant batch</option></select></label><button className="primary-action" onClick={runBatch} disabled={state === "loading"} data-state={state}>{state === "loading" ? "Running reconciliation…" : "Run reconciliation"}</button>{report && <button className="quiet-action" onClick={reset}>Reset view</button>}</div></section>
    {error && <section className="error-banner" role="alert"><strong>Run unavailable.</strong> {error} <button onClick={runBatch}>Try again</button></section>}
    <section className="metric-grid" aria-label="Batch metrics">{metrics.map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}<article className="metric metric-note"><span>Processing time</span><strong>{report ? `${report.processing_time_ms} ms` : "Awaiting run"}</strong></article></section>
    <section className="review-layout" aria-label="Exception review"><section className="exception-panel" aria-labelledby="exceptions-heading"><div className="panel-heading"><div><p className="eyebrow">Review queue</p><h2 id="exceptions-heading">Exceptions requiring attention</h2></div><span className="count-badge">{report ? exceptions.length : "—"}</span></div>{!report && <div className="empty-state"><strong>No batch has been run.</strong><p>Run the synthetic batch to see unresolved and ambiguous cases.</p></div>}{exceptions.map((decision) => <button className={`exception-row ${selected?.source_id === decision.source_id ? "is-selected" : ""}`} key={decision.source_id} onClick={() => setSelectedId(decision.source_id)} aria-pressed={selected?.source_id === decision.source_id}><span className={`status-dot ${decision.status}`} aria-hidden="true"/><span className="exception-main"><strong>{decision.source_id}</strong><small>{words(decision.exception_category ?? decision.status)}</small></span><span className="row-status">{decision.status}</span></button>)}</section>
    <aside className="evidence-panel" aria-labelledby="evidence-heading"><p className="eyebrow">Inspectable evidence</p><h2 id="evidence-heading">{selected ? selected.source_id : "Select an exception"}</h2>{selected ? <><dl className="record-facts"><div><dt>Outcome</dt><dd>{selected.status}</dd></div><div><dt>Relationship</dt><dd>{words(selected.relationship)}</dd></div><div><dt>Confidence</dt><dd>{Math.round(selected.confidence * 100)}%</dd></div><div><dt>Candidate</dt><dd>{selected.target_id ?? "No safe candidate"}</dd></div></dl><h3>Why it stopped</h3><ul className="evidence-list">{selected.evidence.map((item) => <li key={item}>{item}</li>)}</ul><p className="review-boundary">No AI recommendation or financial change is available in Phase 2. This item remains unresolved by design.</p></> : <p className="empty-copy">Evidence will appear after a batch is run.</p>}</aside></section>
    <section className="category-strip" aria-label="Exception categories"><p className="eyebrow">Exception mix</p>{report ? Object.entries(report.exception_categories).map(([category, count]) => <div className="category" key={category}><span>{words(category)}</span><strong>{count}</strong></div>) : <p className="empty-copy">Categories will be calculated from the completed run.</p>}</section>
  </main>;
}
