"use client";

import { useMemo, useState } from "react";

type Decision = { source_id: string; target_id: string | null; relationship: string; status: "matched" | "unmatched" | "ambiguous"; confidence: number; rule_id: string | null; evidence: string[]; exception_category: string | null };
type Report = { records_processed: number; auto_match_rate: number; verified_matching_accuracy: number; unresolved_exceptions: number; processing_time_ms: number; exception_categories: Record<string, number>; decisions: Decision[] };
type Analysis = { status: "available" | "unavailable"; classification: string | null; explanation: string | null; recommendation: string | null; confidence: number | null; limitation: string };
type AuditEvent = { id: string; event_type: string; entity_id: string; created_at: string; payload: Record<string, unknown> };
const words = (value: string) => value.replaceAll("_", " ");

export function ReconciliationWorkbench() {
  const [report, setReport] = useState<Report | null>(null);
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle");
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [analysisState, setAnalysisState] = useState<"idle" | "loading" | "error">("idle");
  const [auditEvents, setAuditEvents] = useState<AuditEvent[]>([]);
  const [resolutionMessage, setResolutionMessage] = useState<string | null>(null);
  const exceptions = useMemo(() => report?.decisions.filter((decision) => decision.status !== "matched") ?? [], [report]);
  const selected = exceptions.find((decision) => decision.source_id === selectedId) ?? exceptions[0] ?? null;
  async function loadAudit() { const response = await fetch("/api/audit-events"); if (response.ok) setAuditEvents((await response.json()).events); }
  async function runBatch() { setState("loading"); setError(null); try { const response = await fetch("/api/reconciliation", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "The reconciliation run could not complete."); setReport(body); setSelectedId(null); setAnalysis(null); setResolutionMessage(null); setState("success"); void loadAudit(); } catch (cause) { setError(cause instanceof Error ? cause.message : "The reconciliation run could not complete."); setState("error"); } }
  async function analyze() { if (!selected) return; setAnalysisState("loading"); try { const response = await fetch("/api/exception-analysis", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision: selected }) }); const body = await response.json(); if (!response.ok) throw new Error(); setAnalysis(body); setAnalysisState("idle"); } catch { setAnalysisState("error"); } }
  async function resolve(action: "approved" | "rejected") { if (!selected || !analysis) return; const response = await fetch("/api/resolutions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision: selected, analysis, action, actor_label: "Demo finance reviewer", rationale: action === "approved" ? "Evidence reviewed; proposed follow-up accepted." : "Evidence reviewed; proposed follow-up rejected." }) }); const body = await response.json(); setResolutionMessage(response.ok ? body.message : body.detail); void loadAudit(); }
  function reset() { setReport(null); setSelectedId(null); setAnalysis(null); setError(null); setState("idle"); }
  const metrics = [["Records processed", report ? String(report.records_processed) : "—"], ["Auto-match rate", report ? `${Math.round(report.auto_match_rate * 100)}%` : "—"], ["Verified accuracy", report ? `${Math.round(report.verified_matching_accuracy * 100)}%` : "—"], ["Unresolved", report ? String(report.unresolved_exceptions) : "—"]];
  return <main className="workbench">
    <header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true">L</span>LedgerLens</div><p className="source-label">Synthetic demo data only · no live Razorpay integration</p></header>
    <section className="runbar" aria-labelledby="workspace-heading"><div><p className="eyebrow">Reconciliation workspace</p><h1 id="workspace-heading">Close the batch. Keep the uncertainty visible.</h1><p className="lede">Deterministic rules reconcile the evidence. Exceptions stay open until a human reviews them.</p></div><div className="run-controls"><label className="batch-picker">Batch<select aria-label="Select reconciliation batch" defaultValue="august"><option value="august">August demo merchant batch</option></select></label><button className="primary-action" onClick={runBatch} disabled={state === "loading"} data-state={state}>{state === "loading" ? "Running reconciliation…" : "Run reconciliation"}</button>{report && <button className="quiet-action" onClick={reset}>Reset view</button>}</div></section>
    {error && <section className="error-banner" role="alert"><strong>Run unavailable.</strong> {error} <button onClick={runBatch}>Try again</button></section>}
    <section className="metric-grid" aria-label="Batch metrics">{metrics.map(([label, value]) => <article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}<article className="metric metric-note"><span>Processing time</span><strong>{report ? `${report.processing_time_ms} ms` : "Awaiting run"}</strong></article></section>
    <section className="review-layout" aria-label="Exception review"><section className="exception-panel" aria-labelledby="exceptions-heading"><div className="panel-heading"><div><p className="eyebrow">Review queue</p><h2 id="exceptions-heading">Exceptions requiring attention</h2></div><span className="count-badge">{report ? exceptions.length : "—"}</span></div>{!report && <div className="empty-state"><strong>No batch has been run.</strong><p>Run the synthetic batch to see unresolved and ambiguous cases.</p></div>}{exceptions.map((decision) => <button className={`exception-row ${selected?.source_id === decision.source_id ? "is-selected" : ""}`} key={decision.source_id} onClick={() => { setSelectedId(decision.source_id); setAnalysis(null); }} aria-pressed={selected?.source_id === decision.source_id}><span className={`status-dot ${decision.status}`} aria-hidden="true"/><span className="exception-main"><strong>{decision.source_id}</strong><small>{words(decision.exception_category ?? decision.status)}</small></span><span className="row-status">{decision.status}</span></button>)}</section>
    <aside className="evidence-panel" aria-labelledby="evidence-heading"><p className="eyebrow">Inspectable evidence</p><h2 id="evidence-heading">{selected ? selected.source_id : "Select an exception"}</h2>{selected ? <><dl className="record-facts"><div><dt>Outcome</dt><dd>{selected.status}</dd></div><div><dt>Relationship</dt><dd>{words(selected.relationship)}</dd></div><div><dt>Confidence</dt><dd>{Math.round(selected.confidence * 100)}%</dd></div><div><dt>Candidate</dt><dd>{selected.target_id ?? "No safe candidate"}</dd></div></dl><h3>Why it stopped</h3><ul className="evidence-list">{selected.evidence.map((item) => <li key={item}>{item}</li>)}</ul><button className="analysis-action" onClick={analyze} disabled={analysisState === "loading"}>{analysisState === "loading" ? "Analyzing evidence…" : "Analyze exception"}</button>{analysis?.status === "available" && <section className="analysis-result"><p className="eyebrow">AI advisory</p><strong>{analysis.classification}</strong><p>{analysis.explanation}</p><dl className="analysis-facts"><div><dt>Recommended review</dt><dd>{words(analysis.recommendation ?? "manual_investigation")}</dd></div><div><dt>AI confidence</dt><dd>{Math.round((analysis.confidence ?? 0) * 100)}%</dd></div></dl><div className="resolution-actions"><button className="approve-action" onClick={() => resolve("approved")}>Approve follow-up</button><button className="quiet-action" onClick={() => resolve("rejected")}>Reject</button></div></section>}{analysis?.status === "unavailable" && <p className="analysis-unavailable">{analysis.limitation} The exception remains unresolved.</p>}{resolutionMessage && <p className="resolution-message">{resolutionMessage}</p>}<p className="review-boundary">AI is advisory only. Human approval records a follow-up only; it cannot alter source financial records.</p></> : <p className="empty-copy">Evidence will appear after a batch is run.</p>}</aside></section>
    <section className="category-strip" aria-label="Exception categories"><p className="eyebrow">Exception mix</p>{report ? Object.entries(report.exception_categories).map(([category, count]) => <div className="category" key={category}><span>{words(category)}</span><strong>{count}</strong></div>) : <p className="empty-copy">Categories will be calculated from the completed run.</p>}</section><section className="audit-panel"><div><p className="eyebrow">Append-only audit trail</p><h2>Latest workflow events</h2></div>{auditEvents.length ? auditEvents.slice(0, 6).map((event) => <article key={event.id}><strong>{words(event.event_type)}</strong><span>{event.entity_id}</span><time>{new Date(event.created_at).toLocaleTimeString()}</time></article>) : <p className="empty-copy">Run a batch to create auditable workflow events.</p>}</section>
  </main>;
}
